[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[workspace]
members = ["programs/agrobench"]

[programs.devnet]
agrobench = "EytN8UaXrfTQc6Pq4AdQbQyJwUX37ddXsV7URayBBLrN"

[programs.localnet]
agrobench = "EytN8UaXrfTQc6Pq4AdQbQyJwUX37ddXsV7URayBBLrN"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'no ts tests; use INTERFACE.md for the Go client'"
